In [1]:
import csv
import glob
import os
import pandas as pd
pd.options.mode.chained_assignment = None  # default='warn'

In [2]:
os.chdir(r"../Data/Twitter/cleaned")
filenames = glob.glob("*cleaned_sentiment*.csv")

combined_df = pd.DataFrame()

for file in filenames:
    df = pd.read_csv(file)
    df['Source'] = ['Twitter'] * df.shape[0]
    df['Stock'] = [file.split('_')[0]] * df.shape[0] 
    combined_df = pd.concat([combined_df, df])

# changing flaire sentiment score to match flaire_sentiment
mask = (combined_df['flair_sentiment'] == 'NEGATIVE')
combined_df['flair_sentiment_score'][mask] *= -1

# removed number of comments and retweets as well
combined_df.drop(columns = ['Unnamed: 0', 'Unnamed: 0.1', 'Username', 'Tweet', 'cleaned Tweet', 'flair_sentiment', 'vader_sentiment', 'Number of Comments', 'Number of Retweets'], inplace = True)

combined_df.head()

,Datetime,Number of Followers,Number of Comments,Number of Retweets,Number of Likes,flair_sentiment_score,vader_score,finbert_sentiment,finbert_score,Source,Stock
0,2021-09-30 18:01:19+00:00,559219,215,442,2532,-0.9999,-0.0772,neutral,0.820654,Twitter,AAPL
1,2021-09-30 15:30:03+00:00,213150,6,17,215,0.7746,0.5267,neutral,0.940475,Twitter,AAPL
2,2021-09-30 13:36:10+00:00,33383,21,68,361,-0.9786,0.0000,neutral,0.831750,Twitter,AAPL
3,2021-09-30 10:19:31+00:00,14836,22,36,237,0.9617,0.3182,neutral,0.935794,Twitter,AAPL
4,2021-09-29 23:24:02+00:00,128553,22,36,224,-0.6766,0.4019,neutral,0.931196,Twitter,AAPL

# Normalizing Data based on day

In [21]:
import datetime

In [7]:
combined_df['Datetime'] = pd.to_datetime(combined_df['Datetime']).dt.date

combined_df.head()

,Datetime,Number of Followers,Number of Comments,Number of Retweets,Number of Likes,flair_sentiment_score,vader_score,finbert_sentiment,finbert_score,Source,Stock
0,2021-09-30,559219,215,442,2532,-0.9999,-0.0772,neutral,0.820654,Twitter,AAPL
1,2021-09-30,213150,6,17,215,0.7746,0.5267,neutral,0.940475,Twitter,AAPL
2,2021-09-30,33383,21,68,361,-0.9786,0.0000,neutral,0.831750,Twitter,AAPL
3,2021-09-30,14836,22,36,237,0.9617,0.3182,neutral,0.935794,Twitter,AAPL
4,2021-09-29,128553,22,36,224,-0.6766,0.4019,neutral,0.931196,Twitter,AAPL

In [9]:

dates = combined_df['Datetime'].unique()
dates.sort()

followers = combined_df.groupby(['Datetime', 'Stock'])['Number of Followers'].max()
likes = combined_df.groupby(['Datetime', 'Stock'])['Number of Likes'].max()
variable_counts = list(zip(followers, likes))


daily_max = {dates[i]: variable_counts[i] for i in range(len(dates))}

In [17]:
#creating dictionary column name : [datetime.date, stock] : max value
#dictionary within a dictionary, first key = column name, second key = [datetime.date, stock]

combined_df.groupby(['Datetime', 'Stock']).max()

daily_max = combined_df.groupby(['Datetime', 'Stock']).max().apply(lambda x : x .to_list()).to_dict()

{'Number of Followers': {(datetime.date(2021, 1, 1), 'AAPL'): 68944,
  (datetime.date(2021, 1, 1), 'AMZN'): 33317,
  (datetime.date(2021, 1, 1), 'ARKK'): 33151,
  (datetime.date(2021, 1, 1), 'GOOGL'): 33308,
  (datetime.date(2021, 1, 1), 'MSFT'): 33315,
  (datetime.date(2021, 1, 1), 'TSLA'): 589808,
  (datetime.date(2021, 1, 1), 'VXRT'): 44380,
  (datetime.date(2021, 1, 2), 'AAPL'): 404183,
  (datetime.date(2021, 1, 2), 'AMZN'): 405443,
  (datetime.date(2021, 1, 2), 'ARKK'): 400,
  (datetime.date(2021, 1, 2), 'GOOGL'): 405384,
  (datetime.date(2021, 1, 2), 'MSFT'): 405422,
  (datetime.date(2021, 1, 2), 'Russell 1000'): 309740,
  (datetime.date(2021, 1, 2), 'TSLA'): 600061,
  (datetime.date(2021, 1, 2), 'VXRT'): 44380,
  (datetime.date(2021, 1, 3), 'AAPL'): 601323,
  (datetime.date(2021, 1, 3), 'AMZN'): 33317,
  (datetime.date(2021, 1, 3), 'ARKK'): 21215,
  (datetime.date(2021, 1, 3), 'MSFT'): 212991,
  (datetime.date(2021, 1, 3), 'TSLA'): 243474,
  (datetime.date(2021, 1, 4), 'AAPL'): 33057,
  (datetime.date(2021, 1, 4), 'AMZN'): 415563,
  (datetime.date(2021, 1, 4), 'ARKK'): 107004,
  (datetime.date(2021, 1, 4), 'GOOGL'): 1210033,
  (datetime.date(2021, 1, 4), 'MSFT'): 196050,
  (datetime.date(2021, 1, 4), 'TSLA'): 1103282,
  (datetime.date(2021, 1, 5), 'AAPL'): 91933,
  (datetime.date(2021, 1, 5), 'AMZN'): 399099,
  (datetime.date(2021, 1, 5), 'ARKK'): 123658,
  (datetime.date(2021, 1, 5), 'ATER'): 8895,
  (datetime.date(2021, 1, 5), 'GOOGL'): 73988,
  (datetime.date(2021, 1, 5), 'MSFT'): 212990,
  (datetime.date(2021, 1, 5), 'TSLA'): 1141372,
  (datetime.date(2021, 1, 6), 'AAPL'): 594372,
  (datetime.date(2021, 1, 6), 'AMZN'): 599669,
  (datetime.date(2021, 1, 6), 'ATER'): 334257,
  (datetime.date(2021, 1, 6), 'GOOGL'): 599487,
  (datetime.date(2021, 1, 6), 'MSFT'): 599564,
  (datetime.date(2021, 1, 6), 'TSLA'): 502745,
  (datetime.date(2021, 1, 7), 'AAPL'): 1748520,
  (datetime.date(2021, 1, 7), 'AMZN'): 316068,
  (datetime.date(2021, 1, 7), 'ARKK'): 107004,
  (datetime.date(2021, 1, 7), 'ATER'): 1428,
  (datetime.date(2021, 1, 7), 'GOOGL'): 85540,
  (datetime.date(2021, 1, 7), 'MSFT'): 1751862,
  (datetime.date(2021, 1, 7), 'TSLA'): 600045,
  (datetime.date(2021, 1, 8), 'AAPL'): 594364,
  (datetime.date(2021, 1, 8), 'AMZN'): 405438,
  (datetime.date(2021, 1, 8), 'ARKK'): 40054,
  (datetime.date(2021, 1, 8), 'MSFT'): 320704,
  (datetime.date(2021, 1, 8), 'TSLA'): 2268936,
  (datetime.date(2021, 1, 9), 'AAPL'): 594363,
  (datetime.date(2021, 1, 9), 'AMZN'): 75879,
  (datetime.date(2021, 1, 9), 'GOOGL'): 33308,
  (datetime.date(2021, 1, 9), 'TSLA'): 502741,
  (datetime.date(2021, 1, 10), 'AAPL'): 315146,
  (datetime.date(2021, 1, 10), 'AMZN'): 121173,
  (datetime.date(2021, 1, 10), 'MSFT'): 11360,
  (datetime.date(2021, 1, 10), 'TSLA'): 386042,
  (datetime.date(2021, 1, 11), 'AAPL'): 60218,
  (datetime.date(2021, 1, 11), 'AMZN'): 599660,
  (datetime.date(2021, 1, 11), 'ARKK'): 92601,
  (datetime.date(2021, 1, 11), 'ATER'): 78,
  (datetime.date(2021, 1, 11), 'GOOGL'): 315564,
  (datetime.date(2021, 1, 11), 'MSFT'): 315577,
  (datetime.date(2021, 1, 11), 'TSLA'): 502739,
  (datetime.date(2021, 1, 12), 'AAPL'): 195426,
  (datetime.date(2021, 1, 12), 'AMZN'): 601074,
  (datetime.date(2021, 1, 12), 'ATER'): 66273,
  (datetime.date(2021, 1, 12), 'GOOGL'): 333,
  (datetime.date(2021, 1, 12), 'MSFT'): 212989,
  (datetime.date(2021, 1, 12), 'TSLA'): 402604,
  (datetime.date(2021, 1, 13), 'AAPL'): 85236,
  (datetime.date(2021, 1, 13), 'AMZN'): 85556,
  (datetime.date(2021, 1, 13), 'ARKK'): 68476,
  (datetime.date(2021, 1, 13), 'ATER'): 15708,
  (datetime.date(2021, 1, 13), 'MSFT'): 31258,
  (datetime.date(2021, 1, 13), 'TSLA'): 1148291,
  (datetime.date(2021, 1, 14), 'AAPL'): 85238,
  (datetime.date(2021, 1, 14), 'AMZN'): 141725,
  (datetime.date(2021, 1, 14), 'TSLA'): 600038,
  (datetime.date(2021, 1, 15), 'AAPL'): 282191,
  (datetime.date(2021, 1, 15), 'AMZN'): 213000,
  (datetime.date(2021, 1, 15), 'ARKK'): 288784,
  (datetime.date(2021, 1, 15), 'MSFT'): 283548,
  (datetime.date(2021, 1, 15), 'TSLA'): 502734,
  (datetime.date(2021, 1, 16), 'AAPL'): 81719,
  (datetime.date(2021, 1, 16), 'AMZN'): 85554,
  (datetime.date(2021, 1, 16), 'ARKK'): 31589,
  (datetime.date(2021, 1, 16), 'ATER'): 203367,
  (datetime.date(2021, 1, 16), 'TSLA'): 213191,
  (datetime.date(2021, 1, 17), 'AAPL'): 55525,
  (datetime.date(2021, 1, 17), 'AMZN'): 57210,
  (datetime.date(2021, 1, 17), 'TSLA'): 123965,
  (datetime.date(2021, 1, 18), 'AAPL'): 123862,
  (datetime.date(2021, 1, 18), 'AMZN'): 102073,
  (datetime.date(2021, 1, 18), 'MSFT'): 102067,
  (datetime.date(2021, 1, 18), 'TSLA'): 600032,
  (datetime.date(2021, 1, 19), 'AAPL'): 1098060,
  (datetime.date(2021, 1, 19), 'AMZN'): 85554,
  (datetime.date(2021, 1, 19), 'ARKK'): 288784,
  (datetime.date(2021, 1, 19), 'ATER'): 57810,
  (datetime.date(2021, 1, 19), 'GOOGL'): 33308,
  (datetime.date(2021, 1, 19), 'MSFT'): 33315,
  (datetime.date(2021, 1, 19), 'TSLA'): 502732,
  (datetime.date(2021, 1, 20), 'AAPL'): 129757,
  (datetime.date(2021, 1, 20), 'AMZN'): 383595,
  (datetime.date(2021, 1, 20), 'GOOGL'): 129830,
  (datetime.date(2021, 1, 20), 'TSLA'): 601399,
  (datetime.date(2021, 1, 21), 'AAPL'): 483857,
  (datetime.date(2021, 1, 21), 'AMZN'): 383595,
  (datetime.date(2021, 1, 21), 'ARKK'): 311984,
  (datetime.date(2021, 1, 21), 'MSFT'): 331419,
  (datetime.date(2021, 1, 21), 'TSLA'): 316132,
  (datetime.date(2021, 1, 22), 'AAPL'): 105386,
  (datetime.date(2021, 1, 22), 'AMZN'): 188834,
  (datetime.date(2021, 1, 22), 'ARKK'): 31589,
  (datetime.date(2021, 1, 22), 'GOOGL'): 99088,
  (datetime.date(2021, 1, 22), 'MSFT'): 188825,
  (datetime.date(2021, 1, 22), 'TSLA'): 213191,
  (datetime.date(2021, 1, 23), 'AAPL'): 282189,
  (datetime.date(2021, 1, 23), 'AMZN'): 85555,
  (datetime.date(2021, 1, 23), 'MSFT'): 283548,
  (datetime.date(2021, 1, 23), 'TSLA'): 283858,
  (datetime.date(2021, 1, 24), 'AAPL'): 258787,
  (datetime.date(2021, 1, 24), 'AMZN'): 601066,
  (datetime.date(2021, 1, 24), 'MSFT'): 123060,
  (datetime.date(2021, 1, 24), 'TSLA'): 374922,
  (datetime.date(2021, 1, 25), 'AAPL'): 258787,
  (datetime.date(2021, 1, 25), 'AMZN'): 89030,
  (datetime.date(2021, 1, 25), 'ARKK'): 3470,
  (datetime.date(2021, 1, 25), 'GOOGL'): 61891,
  (datetime.date(2021, 1, 25), 'MSFT'): 243257,
  (datetime.date(2021, 1, 25), 'TSLA'): 567226,
  (datetime.date(2021, 1, 25), 'VXRT'): 5890,
  (datetime.date(2021, 1, 26), 'AAPL'): 313949,
  (datetime.date(2021, 1, 26), 'AMZN'): 315596,
  (datetime.date(2021, 1, 26), 'GOOGL'): 316044,
  (datetime.date(2021, 1, 26), 'MSFT'): 699155,
  (datetime.date(2021, 1, 26), 'TSLA'): 600020,
  (datetime.date(2021, 1, 27), 'AAPL'): 697919,
  (datetime.date(2021, 1, 27), 'AMZN'): 599652,
  (datetime.date(2021, 1, 27), 'GOOGL'): 33307,
  (datetime.date(2021, 1, 27), 'MSFT'): 599550,
  (datetime.date(2021, 1, 27), 'TSLA'): 1141381,
  (datetime.date(2021, 1, 28), 'AAPL'): 174363,
  (datetime.date(2021, 1, 28), 'AMZN'): 663602,
  (datetime.date(2021, 1, 28), 'ARKK'): 2834425,
  (datetime.date(2021, 1, 28), 'MSFT'): 58273,
  (datetime.date(2021, 1, 28), 'TSLA'): 812661,
  (datetime.date(2021, 1, 29), 'AAPL'): 594323,
  (datetime.date(2021, 1, 29), 'AMZN'): 599650,
  (datetime.date(2021, 1, 29), 'ARKK'): 75800,
  (datetime.date(2021, 1, 29), 'MSFT'): 599548,
  (datetime.date(2021, 1, 29), 'TSLA'): 1141384,
  (datetime.date(2021, 1, 29), 'VXRT'): 58303,
  (datetime.date(2021, 1, 30), 'AAPL'): 382788,
  (datetime.date(2021, 1, 30), 'AMZN'): 283560,
  (datetime.date(2021, 1, 30), 'ARKK'): 288783,
  (datetime.date(2021, 1, 30), 'GOOGL'): 283528,
  (datetime.date(2021, 1, 30), 'MSFT'): 58273,
  (datetime.date(2021, 1, 30), 'TSLA'): 14995942,
  (datetime.date(2021, 1, 30), 'VXRT'): 44380,
  (datetime.date(2021, 1, 31), 'AAPL'): 58303,
  (datetime.date(2021, 1, 31), 'AMZN'): 1102710,
  (datetime.date(2021, 1, 31), 'ARKK'): 29589,
  (datetime.date(2021, 1, 31), 'MSFT'): 58273,
  (datetime.date(2021, 1, 31), 'TSLA'): 201884,
  (datetime.date(2021, 2, 1), 'AAPL'): 128655,
  (datetime.date(2021, 2, 1), 'AMZN'): 121378,
  (datetime.date(2021, 2, 1), 'ARKK'): 1906,
  (datetime.date(2021, 2, 1), 'GOOGL'): 99088,
  (datetime.date(2021, 2, 1), 'MSFT'): 243255,
  (datetime.date(2021, 2, 1), 'TSLA'): 1141383,
  (datetime.date(2021, 2, 2), 'AAPL'): 309825,
  (datetime.date(2021, 2, 2), 'AMZN'): 23890276,
  (datetime.date(2021, 2, 2), 'GOOGL'): 1102420,
  (datetime.date(2021, 2, 2), 'MSFT'): 312005,
  (datetime.date(2021, 2, 2), 'TSLA'): 502722,
  (datetime.date(2021, 2, 2), 'VXRT'): 5890,
  (datetime.date(2021, 2, 3), 'AAPL'): 309825,
  (datetime.date(2021, 2, 3), 'AMZN'): 312017,
  (datetime.date(2021, 2, 3), 'ARKK'): 29589,
  (datetime.date(2021, 2, 3), 'ATER'): 15173,
  (datetime.date(2021, 2, 3), 'GOOGL'): 311987,
  (datetime.date(2021, 2, 3), 'MSFT'): 312005,
  (datetime.date(2021, 2, 3), 'TSLA'): 175498,
  (datetime.date(2021, 2, 3), 'VXRT'): 5890,
  (datetime.date(2021, 2, 4), 'AAPL'): 315136,
  (datetime.date(2021, 2, 4), 'AMZN'): 1587101,
  (datetime.date(2021, 2, 4), 'ARKK'): 71640,
  (datetime.date(2021, 2, 4), 'ATER'): 16962556,
  (datetime.date(2021, 2, 4), 'GOOGL'): 311987,
  (datetime.date(2021, 2, 4), 'MSFT'): 312005,
  (datetime.date(2021, 2, 4), 'TSLA'): 600000,
  (datetime.date(2021, 2, 5), 'AAPL'): 188313,
  (datetime.date(2021, 2, 5), 'AMZN'): 383554,
  (datetime.date(2021, 2, 5), 'ARKK'): 288782,
  (datetime.date(2021, 2, 5), 'ATER'): 76938,
  (datetime.date(2021, 2, 5), 'MSFT'): 58273,
  (datetime.date(2021, 2, 5), 'TSLA'): 331483,
  (datetime.date(2021, 2, 6), 'AAPL'): 117565,
  (datetime.date(2021, 2, 6), 'AMZN'): 29022,
  (datetime.date(2021, 2, 6), 'ARKK'): 8629,
  (datetime.date(2021, 2, 6), 'ATER'): 646,
  (datetime.date(2021, 2, 6), 'MSFT'): 29594,
  (datetime.date(2021, 2, 6), 'TSLA'): 175498,
  (datetime.date(2021, 2, 7), 'AAPL'): 7332,
  (datetime.date(2021, 2, 7), 'AMZN'): 174159,
  (datetime.date(2021, 2, 7), 'ARKK'): 11518,
  (datetime.date(2021, 2, 7), 'GOOGL'): 49522,
  (datetime.date(2021, 2, 7), 'MSFT'): 8331,
  (datetime.date(2021, 2, 7), 'TSLA'): 174177,
  (datetime.date(2021, 2, 8), 'AAPL'): 859562,
  (datetime.date(2021, 2, 8), 'AMZN'): 859421,
  (datetime.date(2021, 2, 8), 'ARKK'): 50664,
  (datetime.date(2021, 2, 8), 'ATER'): 1827,
  (datetime.date(2021, 2, 8), 'TSLA'): 4320468,
  (datetime.date(2021, 2, 9), 'AAPL'): 1142209,
  (datetime.date(2021, 2, 9), 'AMZN'): 320739,
  (datetime.date(2021, 2, 9), 'ARKK'): 311983,
  (datetime.date(2021, 2, 9), 'ATER'): 7114,
  (datetime.date(2021, 2, 9), 'GOOGL'): 320649,
  (datetime.date(2021, 2, 9), 'MSFT'): 320693,
  (datetime.date(2021, 2, 9), 'TSLA'): 2960092,
  (datetime.date(2021, 2, 10), 'AAPL'): 594304,
  (datetime.date(2021, 2, 10), 'AMZN'): 305966,
  (datetime.date(2021, 2, 10), 'ARKK'): 40737,
  (datetime.date(2021, 2, 10), 'ATER'): 46980,
  (datetime.date(2021, 2, 10), 'MSFT'): 34355,
  (datetime.date(2021, 2, 10), 'TSLA'): 601377,
  (datetime.date(2021, 2, 11), 'AMZN'): 61400,
  (datetime.date(2021, 2, 11), 'ARKK'): 288781,
  (datetime.date(2021, 2, 11), 'MSFT'): 143144,
  (datetime.date(2021, 2, 11), 'TSLA'): 502713,
  (datetime.date(2021, 2, 12), 'AAPL'): 570227,
  (datetime.date(2021, 2, 12), 'AMZN'): 243276,
  (datetime.date(2021, 2, 12), 'ARKK'): 117577,
  (datetime.date(2021, 2, 12), 'ATER'): 1624,
  (datetime.date(2021, 2, 12), 'GOOGL'): 127675,
  (datetime.date(2021, 2, 12), 'TSLA'): 305940,
  (datetime.date(2021, 2, 13), 'AAPL'): 29274,
  (datetime.date(2021, 2, 13), 'AMZN'): 29598,
  (datetime.date(2021, 2, 13), 'ARKK'): 117577,
  (datetime.date(2021, 2, 13), 'GOOGL'): 5944,
  (datetime.date(2021, 2, 13), 'MSFT'): 5944,
  (datetime.date(2021, 2, 13), 'TSLA'): 1802500,
  (datetime.date(2021, 2, 14), 'AAPL'): 258671,
  (datetime.date(2021, 2, 14), 'AMZN'): 107034,
  (datetime.date(2021, 2, 14), 'GOOGL'): 85539,
  (datetime.date(2021, 2, 14), 'MSFT'): 107027,
  (datetime.date(2021, 2, 14), 'TSLA'): 1802498,
  (datetime.date(2021, 2, 15), 'AAPL'): 80090,
  (datetime.date(2021, 2, 15), 'AMZN'): 83730,
  (datetime.date(2021, 2, 15), 'ARKK'): 24867,
  (datetime.date(2021, 2, 15), 'MSFT'): 7275,
  (datetime.date(2021, 2, 15), 'TSLA'): 612120,
  (datetime.date(2021, 2, 16), 'AAPL'): 276923,
  (datetime.date(2021, 2, 16), 'AMZN'): 32677,
  (datetime.date(2021, 2, 16), 'TSLA'): 2704358,
  (datetime.date(2021, 2, 17), 'AAPL'): 318129,
  (datetime.date(2021, 2, 17), 'AMZN'): 383532,
  (datetime.date(2021, 2, 17), 'ARKK'): 75800,
  (datetime.date(2021, 2, 17), 'GOOGL'): 320648,
  (datetime.date(2021, 2, 17), 'MSFT'): 320689,
  (datetime.date(2021, 2, 17), 'TSLA'): 1141389,
  (datetime.date(2021, 2, 18), 'AAPL'): 154477,
  (datetime.date(2021, 2, 18), 'AMZN'): 599628,
  (datetime.date(2021, 2, 18), 'ARKK'): 202859,
  (datetime.date(2021, 2, 18), 'ATER'): 10488,
  (datetime.date(2021, 2, 18), 'GOOGL'): 156976,
  (datetime.date(2021, 2, 18), 'MSFT'): 156999,
  (datetime.date(2021, 2, 18), 'TSLA'): 502710,
  (datetime.date(2021, 2, 19), 'AAPL'): 594088,
  (datetime.date(2021, 2, 19), 'AMZN'): 580209,
  (datetime.date(2021, 2, 19), 'ARKK'): 75800,
  (datetime.date(2021, 2, 19), 'GOOGL'): 579709,
  (datetime.date(2021, 2, 19), 'MSFT'): 579977,
  (datetime.date(2021, 2, 19), 'TSLA'): 599979,
  (datetime.date(2021, 2, 20), 'AAPL'): 35689,
  (datetime.date(2021, 2, 20), 'AMZN'): 53337,
  (datetime.date(2021, 2, 20), 'ARKK'): 123656,
  (datetime.date(2021, 2, 20), 'ATER'): 88483,
  (datetime.date(2021, 2, 20), 'MSFT'): 175367,
  (datetime.date(2021, 2, 20), 'TSLA'): 175488,
  (datetime.date(2021, 2, 20), 'VXRT'): 44380,
  (datetime.date(2021, 2, 21), 'AAPL'): 180453,
  (datetime.date(2021, 2, 21), 'AMZN'): 67989,
  (datetime.date(2021, 2, 21), 'ATER'): 84456,
  (datetime.date(2021, 2, 21), 'GOOGL'): 67968,
  (datetime.date(2021, 2, 21), 'MSFT'): 67982,
  (datetime.date(2021, 2, 21), 'TSLA'): 599972,
  (datetime.date(2021, 2, 22), 'AAPL'): 29496,
  (datetime.date(2021, 2, 22), 'AMZN'): 779472,
  (datetime.date(2021, 2, 22), 'TSLA'): 599972,
  (datetime.date(2021, 2, 23), 'AAPL'): 1623992,
  (datetime.date(2021, 2, 23), 'AMZN'): 1646552,
  (datetime.date(2021, 2, 23), 'ARKK'): 1102351,
  (datetime.date(2021, 2, 23), 'GOOGL'): 85539,
  (datetime.date(2021, 2, 23), 'MSFT'): 1646223,
  (datetime.date(2021, 2, 23), 'TSLA'): 17104710,
  (datetime.date(2021, 2, 24), 'AAPL'): 315104,
  (datetime.date(2021, 2, 24), 'AMZN'): 1751887,
  (datetime.date(2021, 2, 24), 'ARKK'): 249768,
  (datetime.date(2021, 2, 24), 'GOOGL'): 85539,
  (datetime.date(2021, 2, 24), 'MSFT'): 85547,
  (datetime.date(2021, 2, 24), 'TSLA'): 599963,
  (datetime.date(2021, 2, 25), 'AAPL'): 110669,
  (datetime.date(2021, 2, 25), 'AMZN'): 589750,
  (datetime.date(2021, 2, 25), 'ARKK'): 1102352,
  (datetime.date(2021, 2, 25), 'GOOGL'): 3223930,
  (datetime.date(2021, 2, 25), 'MSFT'): 2699,
  (datetime.date(2021, 2, 25), 'TSLA'): 601356,
  (datetime.date(2021, 2, 26), 'AAPL'): 305573,
  (datetime.date(2021, 2, 26), 'AMZN'): 601043,
  (datetime.date(2021, 2, 26), 'ARKK'): 46228,
  (datetime.date(2021, 2, 26), 'ATER'): 521673,
  (datetime.date(2021, 2, 26), 'GOOGL'): 607155,
  (datetime.date(2021, 2, 26), 'MSFT'): 305972,
  (datetime.date(2021, 2, 26), 'TSLA'): 599959,
  (datetime.date(2021, 2, 26), 'VXRT'): 5890,
  (datetime.date(2021, 2, 27), 'AAPL'): 77057,
  (datetime.date(2021, 2, 27), 'AMZN'): 77278,
  (datetime.date(2021, 2, 27), 'ARKK'): 130787,
  (datetime.date(2021, 2, 27), 'GOOGL'): 77278,
  (datetime.date(2021, 2, 27), 'MSFT'): 1435205,
  (datetime.date(2021, 2, 27), 'TSLA'): 175485,
  (datetime.date(2021, 2, 28), 'AAPL'): 594071,
  (datetime.date(2021, 2, 28), 'AMZN'): 129480,
  (datetime.date(2021, 2, 28), 'ARKK'): 8274,
  (datetime.date(2021, 2, 28), 'MSFT'): 11962,
  (datetime.date(2021, 2, 28), 'TSLA'): 599955,
  (datetime.date(2021, 3, 1), 'AAPL'): 597497,
  (datetime.date(2021, 3, 1), 'AMZN'): 31733,
  (datetime.date(2021, 3, 1), 'ARKK'): 16486,
  (datetime.date(2021, 3, 1), 'MSFT'): 151283,
  (datetime.date(2021, 3, 1), 'TSLA'): 1181617,
  (datetime.date(2021, 3, 2), 'AAPL'): 597498,
  (datetime.date(2021, 3, 2), 'AMZN'): 33315,
  (datetime.date(2021, 3, 2), 'MSFT'): 38011,
  (datetime.date(2021, 3, 2), 'Russell 1000'): 6652,
  (datetime.date(2021, 3, 2), 'TSLA'): 599953,
  (datetime.date(2021, 3, 3), 'AAPL'): 1538477,
  (datetime.date(2021, 3, 3), 'AMZN'): 259322,
  (datetime.date(2021, 3, 3), 'ARKK'): 1102347,
  (datetime.date(2021, 3, 3), 'ATER'): 3796,
  (datetime.date(2021, 3, 3), 'GOOGL'): 85540,
  (datetime.date(2021, 3, 3), 'MSFT'): 1751846,
  (datetime.date(2021, 3, 3), 'TSLA'): 272649,
  (datetime.date(2021, 3, 4), 'AAPL'): 128604,
  (datetime.date(2021, 3, 4), 'AMZN'): 212995,
  (datetime.date(2021, 3, 4), 'ARKK'): 180524,
  (datetime.date(2021, 3, 4), 'GOOGL'): 77278,
  (datetime.date(2021, 3, 4), 'MSFT'): 29594,
  (datetime.date(2021, 3, 4), 'TSLA'): 612076,
  (datetime.date(2021, 3, 5), 'AAPL'): 133578,
  (datetime.date(2021, 3, 5), 'AMZN'): 77278,
  (datetime.date(2021, 3, 5), 'ARKK'): 1102346,
  (datetime.date(2021, 3, 5), 'GOOGL'): 77278,
  (datetime.date(2021, 3, 5), 'MSFT'): 40954,
  (datetime.date(2021, 3, 5), 'TSLA'): 1752005,
  (datetime.date(2021, 3, 6), 'AAPL'): 27117,
  (datetime.date(2021, 3, 6), 'AMZN'): 96592,
  (datetime.date(2021, 3, 6), 'ARKK'): 174145,
  (datetime.date(2021, 3, 6), 'MSFT'): 17930,
  (datetime.date(2021, 3, 6), 'TSLA'): 288793,
  (datetime.date(2021, 3, 7), 'AAPL'): 174341,
  (datetime.date(2021, 3, 7), 'AMZN'): 44969,
  (datetime.date(2021, 3, 7), 'ARKK'): 44943,
  (datetime.date(2021, 3, 7), 'MSFT'): 44955,
  (datetime.date(2021, 3, 7), 'TSLA'): 602439,
  (datetime.date(2021, 3, 8), 'AAPL'): 1097593,
  (datetime.date(2021, 3, 8), 'AMZN'): 82134,
  (datetime.date(2021, 3, 8), 'ARKK'): 288782,
  (datetime.date(2021, 3, 8), 'MSFT'): 39336,
  (datetime.date(2021, 3, 8), 'TSLA'): 1103201,
  (datetime.date(2021, 3, 9), 'AAPL'): 23869467,
  (datetime.date(2021, 3, 9), 'AMZN'): 1102625,
  (datetime.date(2021, 3, 9), 'ARKK'): 1102344,
  (datetime.date(2021, 3, 9), 'ATER'): 846418,
  (datetime.date(2021, 3, 9), 'GOOGL'): 77278,
  (datetime.date(2021, 3, 9), 'MSFT'): 1102506,
  (datetime.date(2021, 3, 9), 'TSLA'): 1103200,
  (datetime.date(2021, 3, 10), 'AAPL'): 594076,
  (datetime.date(2021, 3, 10), 'AMZN'): 18486,
  (datetime.date(2021, 3, 10), 'ATER'): 99603,
  (datetime.date(2021, 3, 10), 'TSLA'): 243453,
  (datetime.date(2021, 3, 11), 'AAPL'): 128602,
  (datetime.date(2021, 3, 11), 'AMZN'): 114292,
  (datetime.date(2021, 3, 11), 'MSFT'): 81898,
  (datetime.date(2021, 3, 11), 'TSLA'): 384093,
  (datetime.date(2021, 3, 12), 'AAPL'): 221354,
  (datetime.date(2021, 3, 12), 'AMZN'): 222418,
  (datetime.date(2021, 3, 12), 'ARKK'): 8274,
  (datetime.date(2021, 3, 12), 'MSFT'): 81898,
  (datetime.date(2021, 3, 12), 'TSLA'): 599937,
  (datetime.date(2021, 3, 13), 'AAPL'): 128601,
  (datetime.date(2021, 3, 13), 'ARKK'): 26802,
  (datetime.date(2021, 3, 13), 'MSFT'): 191152,
  (datetime.date(2021, 3, 13), 'TSLA'): 312074,
  (datetime.date(2021, 3, 14), 'AAPL'): 91413,
  (datetime.date(2021, 3, 14), 'GOOGL'): 12294,
  (datetime.date(2021, 3, 14), 'MSFT'): 38578,
  (datetime.date(2021, 3, 14), 'TSLA'): 599933,
  (datetime.date(2021, 3, 15), 'AAPL'): 128601,
  (datetime.date(2021, 3, 15), 'AMZN'): 85549,
  (datetime.date(2021, 3, 15), 'ATER'): 552402,
  (datetime.date(2021, 3, 15), 'GOOGL'): 77278,
  (datetime.date(2021, 3, 15), 'MSFT'): 85545,
  (datetime.date(2021, 3, 15), 'TSLA'): 1752003,
  (datetime.date(2021, 3, 16), 'AAPL'): 128600,
  (datetime.date(2021, 3, 16), 'AMZN'): 85549,
  (datetime.date(2021, 3, 16), 'ARKK'): 74459,
  (datetime.date(2021, 3, 16), 'GOOGL'): 8063,
  (datetime.date(2021, 3, 16), 'MSFT'): 116121,
  (datetime.date(2021, 3, 16), 'TSLA'): 602429,
  (datetime.date(2021, 3, 17), 'AAPL'): 60950,
  (datetime.date(2021, 3, 17), 'AMZN'): 102111,
  (datetime.date(2021, 3, 17), 'MSFT'): 17930,
  (datetime.date(2021, 3, 17), 'TSLA'): 175482,
  (datetime.date(2021, 3, 18), 'AAPL'): 1749111,

<b>sample input to get max followers per day:</b> daily_max['Number of Followers'][(datetime.date(2021, 1, 1), 'AAPL')]

<b>sample output:</b> 68944

# Applying Weighted Sentiment for weekends

In [ ]:
os.chdir('../../../Sentiment Calculator')
%run Weighted_Sentiment.ipynb

In [ ]:
data = group_by_date(combined_df)
weighted_sent = pd.DataFrame(weighted_weekends(data), columns = ['date', 'flair_weighted', 'vader_weighted', 'finbert_weighted'])
weighted_sent