In [61]:
import pandas as pd
import twint
import nest_asyncio
nest_asyncio.apply()
  
 
t = twint.Config()

# t.Username = 'POTUS'
t.Search = 'TSLA'
# t.Geo = "1.290270,103.851959,15km"

t.Since="2021-09-01"
t.Until="2021-09-11"
# t.Until="2021-09-10"
t.Limit = 100000
# t.Limit = 1
t.Lang = "en"
    
t.Filter_retweets = True 

t.Store_csv = True
t.Output = "TSLA_twitter_test.csv"

t.Pandas = True

t.Custom["tweet"] = ["tweet", "username", "date", "time", "likes_count"]

twint.run.Search(t)

 
df = twint.storage.panda.Tweets_df #result is saved to df
# tweets = df[['tweet','username']]

[!] No more data! Scraping will stop now.
found 0 deleted tweets in this search.

In [62]:
tweets

                                                tweet        username
0   $AMZN Liking the look on this name here. Healt...    PandaOptions
1   @EliBurton_ @garyvee @veefriends @whatsinside ...  Julian68889307
2   🚨 WATCH LIST UPDATE FROM LAST NIGHT PART 4 🚨 :...  StockTraderHub
3   @CoyoteThugly @HibbsA @TaylorOgan @1sthand2 @T...        TeslaJLP
4   @TeslaJLP @1sthand2 @HibbsA @TaylorOgan @Tesla...    CoyoteThugly
5   @EntitledCycling @elonmusk @Tesla Driverless i...      ValleyDuke
6   Ton of haters hitting lately, especially those...     Blaine_Tarr
7                                        @Camp4 $TSLA     justuseapen
8   🤔 Some traders can’t wait to buy contracts aft...        thuhkang
9   @TeslaJLP @HibbsA @TaylorOgan @1sthand2 @Tesla...    CoyoteThugly
10  @RostikRusev @Tesla @papacthulu @RagnarCM @rea...     wilde_dylan
11  @marecare1971 @ekno1949 @madaznfootballr I thi...  johnDlikeabaus
12  Union puppet. Don't get me wrong, better than ...     EBITDAtiger
13  I just did it! Got my #weekendruined, @ScottMo...        Model3AU
14  @CoyoteThugly @1sthand2 @HibbsA @TaylorOgan @T...        TeslaJLP
15  @TeslaJLP @HibbsA @TaylorOgan @1sthand2 @Tesla...    CoyoteThugly
16  $ETSY Nice breakout of consolidation today ove...    PandaOptions
17        Kind of agree. $TSLA $BTC. That’s about it.         Umbisam

In [92]:
def twint_search(search_term, since, until, save_path):
    c = twint.Config()
    c.Search = search_term
    c.Lang = "en"
    c.Since = since.strftime('%Y-%m-%d %H:%M:%S')
    c.Until = until.strftime('%Y-%m-%d %H:%M:%S')
    c.Hide_output = True
    c.Store_json = True
    c.Output = save_path
    twint.run.Search(c)
    
def twint_search_loop(search_term, start_date, end_date, save_dir):
    try:
        os.makedirs(os.path.join(os.getcwd(),save_dir,search_term))
        print(f'Successfully created the directory {os.path.join(os.getcwd(),save_dir,search_term)}')
    except FileExistsError:
        print(f'Directory {os.path.join(os.getcwd(),save_dir,search_term)} already exists')
    
    date_range = pd.date_range(start_date, end_date)
    
    for single_date in date_range:
        since = single_date
        until = single_date + dt.timedelta(days=1)
        save_path = os.path.join(save_dir, search_term, f'{single_date:%Y%m%d}.json')
        print(save_path)
        print(f"Searching for tweets containing '{search_term}' from {single_date:%Y-%m-%d} and saving into {save_path}")
        twint_search(search_term, since, until, save_path)

In [103]:
search_term = 'TSLA'
start_date = dt.datetime(2021, 8, 27)
end_date = dt.datetime(2021, 9, 27)
save_dir = 'data/'

# run search
twint_search_loop(search_term, start_date, end_date, save_dir)

Directory C:\Users\Shawn\test\data/TSLA already exists
data/TSLA\20210827.json
Searching for tweets containing 'TSLA' from 2021-08-27 and saving into data/TSLA\20210827.json
[!] No more data! Scraping will stop now.
found 0 deleted tweets in this search.
data/TSLA\20210828.json
Searching for tweets containing 'TSLA' from 2021-08-28 and saving into data/TSLA\20210828.json
[!] No more data! Scraping will stop now.
found 0 deleted tweets in this search.
data/TSLA\20210829.json
Searching for tweets containing 'TSLA' from 2021-08-29 and saving into data/TSLA\20210829.json
[!] No more data! Scraping will stop now.
found 0 deleted tweets in this search.
data/TSLA\20210830.json
Searching for tweets containing 'TSLA' from 2021-08-30 and saving into data/TSLA\20210830.json
[!] No more data! Scraping will stop now.
found 0 deleted tweets in this search.
data/TSLA\20210831.json
Searching for tweets containing 'TSLA' from 2021-08-31 and saving into data/TSLA\20210831.json
[!] No more data! Scraping will stop now.
found 0 deleted tweets in this search.
data/TSLA\20210901.json
Searching for tweets containing 'TSLA' from 2021-09-01 and saving into data/TSLA\20210901.json
[!] No more data! Scraping will stop now.
found 0 deleted tweets in this search.
data/TSLA\20210902.json
Searching for tweets containing 'TSLA' from 2021-09-02 and saving into data/TSLA\20210902.json
[!] No more data! Scraping will stop now.
found 0 deleted tweets in this search.
data/TSLA\20210903.json
Searching for tweets containing 'TSLA' from 2021-09-03 and saving into data/TSLA\20210903.json
[!] No more data! Scraping will stop now.
found 0 deleted tweets in this search.
data/TSLA\20210904.json
Searching for tweets containing 'TSLA' from 2021-09-04 and saving into data/TSLA\20210904.json
[!] No more data! Scraping will stop now.
found 0 deleted tweets in this search.
data/TSLA\20210905.json
Searching for tweets containing 'TSLA' from 2021-09-05 and saving into data/TSLA\20210905.json
[!] No more data! Scraping will stop now.
found 0 deleted tweets in this search.
data/TSLA\20210906.json
Searching for tweets containing 'TSLA' from 2021-09-06 and saving into data/TSLA\20210906.json
[!] No more data! Scraping will stop now.
found 0 deleted tweets in this search.
data/TSLA\20210907.json
Searching for tweets containing 'TSLA' from 2021-09-07 and saving into data/TSLA\20210907.json
[!] No more data! Scraping will stop now.
found 0 deleted tweets in this search.
data/TSLA\20210908.json
Searching for tweets containing 'TSLA' from 2021-09-08 and saving into data/TSLA\20210908.json
[!] No more data! Scraping will stop now.
found 0 deleted tweets in this search.
data/TSLA\20210909.json
Searching for tweets containing 'TSLA' from 2021-09-09 and saving into data/TSLA\20210909.json
[!] No more data! Scraping will stop now.
found 0 deleted tweets in this search.
data/TSLA\20210910.json
Searching for tweets containing 'TSLA' from 2021-09-10 and saving into data/TSLA\20210910.json
[!] No more data! Scraping will stop now.
found 0 deleted tweets in this search.
data/TSLA\20210911.json
Searching for tweets containing 'TSLA' from 2021-09-11 and saving into data/TSLA\20210911.json
[!] No more data! Scraping will stop now.
found 0 deleted tweets in this search.
data/TSLA\20210912.json
Searching for tweets containing 'TSLA' from 2021-09-12 and saving into data/TSLA\20210912.json
[!] No more data! Scraping will stop now.
found 0 deleted tweets in this search.
data/TSLA\20210913.json
Searching for tweets containing 'TSLA' from 2021-09-13 and saving into data/TSLA\20210913.json
[!] No more data! Scraping will stop now.
found 0 deleted tweets in this search.
data/TSLA\20210914.json
Searching for tweets containing 'TSLA' from 2021-09-14 and saving into data/TSLA\20210914.json
[!] No more data! Scraping will stop now.
found 0 deleted tweets in this search.
data/TSLA\20210915.json
Searching for tweets containing 'TSLA' from 2021-09-15 and saving into data/TSLA\20210915.json
[!] No more data! Scraping will stop now.
found 0 deleted tweets in this search.
data/TSLA\20210916.json
Searching for tweets containing 'TSLA' from 2021-09-16 and saving into data/TSLA\20210916.json
[!] No more data! Scraping will stop now.
found 0 deleted tweets in this search.
data/TSLA\20210917.json
Searching for tweets containing 'TSLA' from 2021-09-17 and saving into data/TSLA\20210917.json
[!] No more data! Scraping will stop now.
found 0 deleted tweets in this search.
data/TSLA\20210918.json
Searching for tweets containing 'TSLA' from 2021-09-18 and saving into data/TSLA\20210918.json
[!] No more data! Scraping will stop now.
found 0 deleted tweets in this search.
data/TSLA\20210919.json
Searching for tweets containing 'TSLA' from 2021-09-19 and saving into data/TSLA\20210919.json
[!] No more data! Scraping will stop now.
found 0 deleted tweets in this search.
data/TSLA\20210920.json
Searching for tweets containing 'TSLA' from 2021-09-20 and saving into data/TSLA\20210920.json
[!] No more data! Scraping will stop now.
found 0 deleted tweets in this search.
data/TSLA\20210921.json
Searching for tweets containing 'TSLA' from 2021-09-21 and saving into data/TSLA\20210921.json
[!] No more data! Scraping will stop now.
found 0 deleted tweets in this search.
data/TSLA\20210922.json
Searching for tweets containing 'TSLA' from 2021-09-22 and saving into data/TSLA\20210922.json
[!] No more data! Scraping will stop now.
found 0 deleted tweets in this search.
data/TSLA\20210923.json
Searching for tweets containing 'TSLA' from 2021-09-23 and saving into data/TSLA\20210923.json
[!] No more data! Scraping will stop now.
found 0 deleted tweets in this search.
data/TSLA\20210924.json
Searching for tweets containing 'TSLA' from 2021-09-24 and saving into data/TSLA\20210924.json
[!] No more data! Scraping will stop now.
found 0 deleted tweets in this search.
data/TSLA\20210925.json
Searching for tweets containing 'TSLA' from 2021-09-25 and saving into data/TSLA\20210925.json
[!] No more data! Scraping will stop now.
found 0 deleted tweets in this search.
data/TSLA\20210926.json
Searching for tweets containing 'TSLA' from 2021-09-26 and saving into data/TSLA\20210926.json
[!] No more data! Scraping will stop now.
found 0 deleted tweets in this search.
data/TSLA\20210927.json
Searching for tweets containing 'TSLA' from 2021-09-27 and saving into data/TSLA\20210927.json
[!] No more data! Scraping will stop now.
found 0 deleted tweets in this search.

In [105]:
# retrieve paths recursively from inside the saved directory
from glob import glob
json_files = glob(os.path.join(save_dir, search_term, '*.json'))

# create DataFrames for each JSON file and combine into a single df
dfs = [pd.read_json(json_file, lines = True) for json_file in json_files]
tweets_df = pd.concat(dfs).reset_index(drop=True)
tweets_df.shape

(72637, 5)

In [106]:
tweets_df.head()

,tweet,username,date,time,likes_count
0,@GraffitiKINGS @Rayong18066450 @IOHK_Charles @...,romandi18547962,2021-08-28,07:59:54,0
1,@IliyaYordanov @tslaqtwin @Tesla @elonmusk @28...,confartabliynu1,2021-08-28,07:59:36,0
2,@Tesla @elonmusk Compare to this one that just...,evfollower1,2021-08-28,07:59:34,0
3,$AAPL no need to overcomplicate things. Price ...,lavineoptions,2021-08-28,07:59:12,0
4,@GraffitiKINGS @IOHK_Charles @Tesla @WAX_io Go...,danmcman77,2021-08-28,07:59:06,0

In [107]:
tweets_df.tail()

,tweet,username,date,time,likes_count
72632,"Tesla, Inc. (TSLA) surprised the market with Q...",goldmansachbot,2021-09-27,08:00:52,0
72633,@kimpaquette @TeslaTruckClub @Hot_Wheels @Tesl...,allanharding,2021-09-27,08:00:50,2
72634,Watchlist $SNAP $FB $NVDA $TSLA $AAPL,tradingwithjuan,2021-09-27,08:00:40,1
72635,Gores Guggenheim SPAC Nears Deal to Combine Wi...,nikolaone1,2021-09-27,08:00:04,0
72636,Stars aligned with positive catalyst $ggpi 🔥⬆️...,aceinformatic,2021-09-27,08:00:02,3

In [108]:
tweets_df.to_csv("combined.csv")